name: Update Trust List

on:
  push:
    branches:
      - main
    paths:
      - "oli/trusted_entities_v2.yml"

jobs:
  attest-trust-list:
    runs-on: ubuntu-latest
    if: github.repository == 'growthepie/gtp-dna'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyyaml oli-python

    - name: Attest trust list
      env:
        OLI_API_KEY: ${{ secrets.OLI_API_KEY }}
      run: |
        python .github/scripts/update_trust_list.py